use std::result;
fn main() {
    let result: Err;
}
